version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
  #    - "443:443"
  #  labels:
  #    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
      - ./current/public:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./pass:/etc/nginx/htpasswd:ro

  #letsencrypt:
  #  image: jrcs/letsencrypt-nginx-proxy-companion
  #  environment:
  #    NGINX_PROXY_CONTAINER: nginx-proxy
  #    NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
  #  volumes:
  #    - ./certs:/etc/nginx/certs:rw
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - ./vhost:/etc/nginx/vhost.d
  #    - ./current/public:/usr/share/nginx/html

  fireflyiii:
    image: jc5x/firefly-iii:latest
    ports:
      - "80"
    deploy:
      replicas: 4
    env_file: .env
    depends_on:
      - fireflyiiidb
      - fireflyiiidb_replica1
      - fireflyiiidb_replica2
      - fireflyiiidb_replica3
      - fireflyiiidb_replica4
  #    - fireflyiiidbcache
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
  
  fireflyiiidb:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_REPLICATION_MODE=master
      - POSTGRES_HOST=fireflyiiidb
      - POSTGRES_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data

  fireflyiiidb_replica1:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_DATABASE=firefly
    volumes:
      - firefly_iii_db_replica1:/var/lib/postgresql/data

  fireflyiiidb_replica2:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_DATABASE=firefly
    volumes:
      - firefly_iii_db_replica2:/var/lib/postgresql/data

  fireflyiiidb_replica3:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_DATABASE=firefly
    volumes:
      - firefly_iii_db_replica3:/var/lib/postgresql/data

  fireflyiiidb_replica4:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_DATABASE=firefly
    volumes:
      - firefly_iii_db_replica4:/var/lib/postgresql/data

  #fireflyiiidbcache:
  #  image: redis:latest
  #  ports:
  #    - "6379"
  #  command: ["redis-server", "--appendonly", "yes"]
  #  volumes:
  #    - firefly_iii_dbcache:/data

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
   firefly_iii_db_replica1:
   firefly_iii_db_replica2:
   firefly_iii_db_replica3:
   firefly_iii_db_replica4:
   #firefly_iii_dbcache:
