version: "3.3"

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "40100:80"
  #    - "443:443"
    deploy:
      replicas: 2
    depends_on:
      - fireflyiii
  #  labels:
  #    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
  #    - ./current/public:/usr/share/nginx/html
  #    - ./certs:/etc/nginx/certs:ro
  #    - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  #    - ./pass:/etc/nginx/htpasswd:ro
    configs:
      - source: firefly3-nginx
        target: /etc/nginx/conf.d/default.conf

  #letsencrypt:
  #  image: jrcs/letsencrypt-nginx-proxy-companion
  #  environment:
  #    NGINX_PROXY_CONTAINER: nginx-proxy
  #    NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
  #  volumes:
  #    - ./certs:/etc/nginx/certs:rw
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - ./vhost:/etc/nginx/vhost.d
  #    - ./current/public:/usr/share/nginx/html

  fireflyiii:
    image: jc5x/firefly-iii:latest
    env_file: .env
    ports:
      - "40110:80"
    depends_on:
      - fireflyiiidb
      - fireflyiiidb_replica1
      - fireflyiiidb_replica2
      - fireflyiiidb_replica3
      - fireflyiiidb_replica4
      - redis_master
      - redis_slave1
      - redis_slave2
      - redis_sentinel1
      - redis_sentinel2
      - redis_sentinel3
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload

  fireflyiii2:
    image: jc5x/firefly-iii:latest
    env_file: .env
    ports:
      - "40111:80"
    depends_on:
      - fireflyiiidb
      - fireflyiiidb_replica1
      - fireflyiiidb_replica2
      - fireflyiiidb_replica3
      - fireflyiiidb_replica4
      - redis_master
      - redis_slave1
      - redis_slave2
      - redis_sentinel1
      - redis_sentinel2
      - redis_sentinel3
    volumes:
      - firefly_iii_export2:/var/www/firefly-iii/storage/export
      - firefly_iii_upload2:/var/www/firefly-iii/storage/upload

  fireflyiii3:
    image: jc5x/firefly-iii:latest
    env_file: .env
    ports:
      - "40112:80"
    depends_on:
      - fireflyiiidb
      - fireflyiiidb_replica1
      - fireflyiiidb_replica2
      - fireflyiiidb_replica3
      - fireflyiiidb_replica4
      - redis_master
      - redis_slave1
      - redis_slave2
      - redis_sentinel1
      - redis_sentinel2
      - redis_sentinel3
    volumes:
      - firefly_iii_export3:/var/www/firefly-iii/storage/export
      - firefly_iii_upload3:/var/www/firefly-iii/storage/upload

  fireflyiii4:
    image: jc5x/firefly-iii:latest
    env_file: .env
    ports:
      - "40113:80"
    depends_on:
      - fireflyiiidb
      - fireflyiiidb_replica1
      - fireflyiiidb_replica2
      - fireflyiiidb_replica3
      - fireflyiiidb_replica4
      - redis_master
      - redis_slave1
      - redis_slave2
      - redis_sentinel1
      - redis_sentinel2
      - redis_sentinel3
    volumes:
      - firefly_iii_export4:/var/www/firefly-iii/storage/export
      - firefly_iii_upload4:/var/www/firefly-iii/storage/upload
  
  fireflyiiidb:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_HOST=fireflyiiidb
      - POSTGRES_REPLICATION_MODE=master
      - POSTGRES_DB_FILE=/run/secrets/firefly3-postgres-db
      - POSTGRES_USER_FILE=/run/secrets/firefly3-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/firefly3-postgres-passwd
      - PGDATA=firefly_iii_db
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
    configs:
      - firefly3-postgresql
      - firefly3-pg_hba
    secrets:
      - firefly3-postgres-db
      - firefly3-postgres-user
      - firefly3-postgres-passwd

  fireflyiiidb_replica1:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_DB_FILE=/run/secrets/firefly3-postgres-db
      - POSTGRES_USER_FILE=/run/secrets/firefly3-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/firefly3-postgres-passwd
      - PGDATA=firefly_iii_db_replica1
    depends_on:
      - fireflyiiidb
    volumes:
      - firefly_iii_db_replica1:/var/lib/postgresql/data
    configs:
      - firefly3-postgresql
      - firefly3-pg_hba
    secrets:
      - firefly3-postgres-db
      - firefly3-postgres-user
      - firefly3-postgres-passwd

  fireflyiiidb_replica2:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_DB_FILE=/run/secrets/firefly3-postgres-db
      - POSTGRES_USER_FILE=/run/secrets/firefly3-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/firefly3-postgres-passwd
      - PGDATA=firefly_iii_db_replica2
    depends_on:
      - fireflyiiidb
    volumes:
      - firefly_iii_db_replica2:/var/lib/postgresql/data
    configs:
      - firefly3-postgresql
      - firefly3-pg_hba
    secrets:
      - firefly3-postgres-db
      - firefly3-postgres-user
      - firefly3-postgres-passwd

  fireflyiiidb_replica3:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_DB_FILE=/run/secrets/firefly3-postgres-db
      - POSTGRES_USER_FILE=/run/secrets/firefly3-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/firefly3-postgres-passwd
      - PGDATA=firefly_iii_db_replica3
    depends_on:
      - fireflyiiidb
    volumes:
      - firefly_iii_db_replica3:/var/lib/postgresql/data
    configs:
      - firefly3-postgresql
      - firefly3-pg_hba
    secrets:
      - firefly3-postgres-db
      - firefly3-postgres-user
      - firefly3-postgres-passwd

  fireflyiiidb_replica4:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_MASTER_HOST=fireflyiiidb
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_DB_FILE=/run/secrets/firefly3-postgres-db
      - POSTGRES_USER_FILE=/run/secrets/firefly3-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/firefly3-postgres-passwd
      - PGDATA=firefly_iii_db_replica4
    depends_on:
      - fireflyiiidb
    volumes:
      - firefly_iii_db_replica4:/var/lib/postgresql/data
    configs:
      - firefly3-postgresql
      - firefly3-pg_hba
    secrets:
      - firefly3-postgres-db
      - firefly3-postgres-user
      - firefly3-postgres-passwd

  redis_master:
    image: redis:latest
    ports:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_master_data:/data

  redis_slave1:
    image: redis:latest
    ports:
      - "6379"
    command: ["redis-server", "--slaveof", "redis_master", "6379"]
    depends_on:
      - redis_master
    volumes:
      - redis_slave_data1:/data

  redis_slave2:
    image: redis:latest
    ports:
      - "6379"
    command: ["redis-server", "--slaveof", "redis_master", "6379"]
    depends_on:
      - redis_master
    volumes:
      - redis_slave_data2:/data

  redis_sentinel1:
    image: bitnami/redis-sentinel:latest
    ports:
      - "26379"
    depends_on:
      - redis_master
    environment:
      - REDIS_MASTER_HOST=redis_master
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

  redis_sentinel2:
    image: bitnami/redis-sentinel:latest
    ports:
      - "26379"
    depends_on:
      - redis_master
    environment:
      - REDIS_MASTER_HOST=redis_master
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

  redis_sentinel3:
    image: bitnami/redis-sentinel:latest
    ports:
      - "26379"
    depends_on:
      - redis_master
    environment:
      - REDIS_MASTER_HOST=redis_master
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

volumes:
  firefly_iii_export:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_export"
  firefly_iii_upload:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_upload"
  firefly_iii_export2:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_export2"
  firefly_iii_upload2:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_upload2"
  firefly_iii_export3:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_export3"
  firefly_iii_upload3:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_upload3"
  firefly_iii_export4:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_export4"
  firefly_iii_upload4:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_upload4"
  firefly_iii_db:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db"
  firefly_iii_db_replica1:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db_replica1"
  firefly_iii_db_replica2:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db_replica2"
  firefly_iii_db_replica3:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db_replica3"
  firefly_iii_db_replica4:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db_replica4"
  redis_master_data:
  redis_slave_data1:
  redis_slave_data2:

configs:
  firefly3-postgresql:
    external: true
  firefly3-pg_hba:
    external: true
  firefly3-nginx:
    external: true

secrets:
  firefly3-postgres-db:
    external: true
  firefly3-postgres-user:
    external: true
  firefly3-postgres-passwd:
    external: true
