version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "30012:80"
  #    - "443:443"
    depends_on:
      - fireflyiii
  #  labels:
  #    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
  #    - ./current/public:/usr/share/nginx/html
  #    - ./certs:/etc/nginx/certs:ro
  #    - ./vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  #    - ./pass:/etc/nginx/htpasswd:ro

  #letsencrypt:
  #  image: jrcs/letsencrypt-nginx-proxy-companion
  #  environment:
  #    NGINX_PROXY_CONTAINER: nginx-proxy
  #    NGINX_DOCKER_GEN_CONTAINER: nginx-proxy
  #  volumes:
  #    - ./certs:/etc/nginx/certs:rw
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - ./vhost:/etc/nginx/vhost.d
  #    - ./current/public:/usr/share/nginx/html

  fireflyiii:
    image: jc5x/firefly-iii:latest
    env_file: .env
    ports:
      - "30012"
    deploy:
      replicas: 4
    depends_on:
      - fireflyiiidb
      - fireflyiiidb_replica
      - redis_master
      - redis_slave
      - redis_sentinel
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
  
  fireflyiiidb:
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=firefly3_postgres_user
      - POSTGRES_PASSWORD=firefly3_postgres_pw
      - POSTGRES_DATABASE=firefly3_postgres_db
      - POSTGRES_REPLICATION_MODE=master
      - POSTGRES_HOST=fireflyiiidb
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
    secrets:
      - firefly3_postgres_user
      - firefly3_postgres_pw
      - firefly3_postgres_db

  fireflyiiidb_replica:
    image: postgres:10-alpine
    ports:
      - "5432"
    deploy:
      replicas: 4
    depends_on:
      - fireflyiiidb
    environment:
      - POSTGRES_USER=firefly3_postgres_user
      - POSTGRES_PASSWORD=firefly3_postgres_pw
      - POSTGRES_DATABASE=firefly3_postgres_db
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_MASTER_HOST=fireflyiiidb
    volumes:
      - firefly_iii_db_replica:/var/lib/postgresql/data
    secrets:
      - firefly3_postgres_user
      - firefly3_postgres_pw
      - firefly3_postgres_db

  redis_master:
    image: redis:latest
    ports:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_master_data:/data

  redis_slave:
    image: redis:latest
    ports:
      - "6379"
    deploy:
      replicas: 2
    command: ["redis-server", "--slaveof", "redis_master", "6379"]
    depends_on:
      - redis_master
    volumes:
      - redis_slave_data:/data

  redis_sentinel:
    image: bitnami/redis-sentinel:latest
    ports:
      - "26379"
    deploy:
      replicas: 2
    depends_on:
      - redis_master
      - redis_slave
    environment:
      - REDIS_MASTER_HOST=redis_master
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    volumes:
      - redis_sentinel_data:/data

volumes:
  firefly_iii_export:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_export"
  firefly_iii_upload:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_upload"
  firefly_iii_db:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db"
  firefly_iii_db_replica:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=srv2-deti.ua.pt,rw"
      device: ":/mnt/nfs/firefly3/firefly_iii_db_replica"
  redis_master_data:
  redis_slave_data:
  redis_sentinel_data:

secrets:
  firefly3_postgres_user:
    external: true
  firefly3_postgres_pw:
    external: true
  firefly3_postgres_db:
    external: true
